server:
  port: 8101

application:
  name: comment-service

database:
  url: 'mysql+pymysql://root:12345678@localhost:3306/socials'
  driver: "pymysql"
  echo: true
  track_modifications: false

services:
  profile_service_url: "http://localhost:8101/comments"
